# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/NACManageDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(515, 678)
        Dialog.setMinimumSize(QtCore.QSize(515, 678))
        Dialog.setMaximumSize(QtCore.QSize(515, 678))
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setContentsMargins(-1, -1, 9, -1)
        self.formLayout.setHorizontalSpacing(4)
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setWordWrap(True)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout.addWidget(self.checkBox_4)
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_5 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_2.addWidget(self.checkBox_5)
        self.checkBox_7 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_2.addWidget(self.checkBox_7)
        self.checkBox_6 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_2.addWidget(self.checkBox_6)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_50 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_50.setObjectName("checkBox_50")
        self.gridLayout_2.addWidget(self.checkBox_50, 9, 3, 1, 1)
        self.checkBox_38 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_38.setObjectName("checkBox_38")
        self.gridLayout_2.addWidget(self.checkBox_38, 5, 3, 1, 1)
        self.checkBox_55 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_55.setObjectName("checkBox_55")
        self.gridLayout_2.addWidget(self.checkBox_55, 12, 2, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_2.addWidget(self.checkBox_23, 12, 0, 1, 1)
        self.checkBox_41 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_41.setObjectName("checkBox_41")
        self.gridLayout_2.addWidget(self.checkBox_41, 6, 3, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_2.addWidget(self.checkBox_17, 6, 0, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout_2.addWidget(self.checkBox_26, 2, 1, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_2.addWidget(self.checkBox_15, 4, 0, 1, 1)
        self.checkBox_52 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_52.setObjectName("checkBox_52")
        self.gridLayout_2.addWidget(self.checkBox_52, 10, 2, 1, 1)
        self.checkBox_47 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_47.setObjectName("checkBox_47")
        self.gridLayout_2.addWidget(self.checkBox_47, 8, 2, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_2.addWidget(self.checkBox_24, 3, 1, 1, 1)
        self.checkBox_44 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_44.setObjectName("checkBox_44")
        self.gridLayout_2.addWidget(self.checkBox_44, 9, 2, 1, 1)
        self.checkBox_46 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_46.setObjectName("checkBox_46")
        self.gridLayout_2.addWidget(self.checkBox_46, 8, 3, 1, 1)
        self.checkBox_43 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_43.setObjectName("checkBox_43")
        self.gridLayout_2.addWidget(self.checkBox_43, 7, 2, 1, 1)
        self.checkBox_30 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_30.setObjectName("checkBox_30")
        self.gridLayout_2.addWidget(self.checkBox_30, 1, 3, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout_2.addWidget(self.checkBox_22, 11, 0, 1, 1)
        self.checkBox_28 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_28.setObjectName("checkBox_28")
        self.gridLayout_2.addWidget(self.checkBox_28, 1, 1, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_2.addWidget(self.checkBox_9, 0, 1, 1, 1)
        self.checkBox_29 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_29.setObjectName("checkBox_29")
        self.gridLayout_2.addWidget(self.checkBox_29, 1, 2, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_2.addWidget(self.checkBox_21, 10, 0, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_2.addWidget(self.checkBox_12, 1, 0, 1, 1)
        self.checkBox_36 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_36.setObjectName("checkBox_36")
        self.gridLayout_2.addWidget(self.checkBox_36, 5, 1, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout_2.addWidget(self.checkBox_20, 9, 0, 1, 1)
        self.checkBox_37 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_37.setObjectName("checkBox_37")
        self.gridLayout_2.addWidget(self.checkBox_37, 5, 2, 1, 1)
        self.checkBox_33 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_33.setObjectName("checkBox_33")
        self.gridLayout_2.addWidget(self.checkBox_33, 4, 1, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_2.addWidget(self.checkBox_14, 3, 0, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_2.addWidget(self.checkBox_11, 0, 3, 1, 1)
        self.checkBox_56 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_56.setObjectName("checkBox_56")
        self.gridLayout_2.addWidget(self.checkBox_56, 12, 3, 1, 1)
        self.checkBox_34 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_34.setObjectName("checkBox_34")
        self.gridLayout_2.addWidget(self.checkBox_34, 4, 2, 1, 1)
        self.checkBox_51 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_51.setObjectName("checkBox_51")
        self.gridLayout_2.addWidget(self.checkBox_51, 10, 1, 1, 1)
        self.checkBox_45 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_45.setObjectName("checkBox_45")
        self.gridLayout_2.addWidget(self.checkBox_45, 7, 3, 1, 1)
        self.checkBox_42 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_42.setObjectName("checkBox_42")
        self.gridLayout_2.addWidget(self.checkBox_42, 7, 1, 1, 1)
        self.checkBox_40 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_40.setObjectName("checkBox_40")
        self.gridLayout_2.addWidget(self.checkBox_40, 6, 2, 1, 1)
        self.checkBox_25 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_25.setObjectName("checkBox_25")
        self.gridLayout_2.addWidget(self.checkBox_25, 3, 2, 1, 1)
        self.checkBox_48 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_48.setObjectName("checkBox_48")
        self.gridLayout_2.addWidget(self.checkBox_48, 8, 1, 1, 1)
        self.checkBox_39 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_39.setObjectName("checkBox_39")
        self.gridLayout_2.addWidget(self.checkBox_39, 6, 1, 1, 1)
        self.checkBox_35 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_35.setObjectName("checkBox_35")
        self.gridLayout_2.addWidget(self.checkBox_35, 4, 3, 1, 1)
        self.checkBox_54 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_54.setObjectName("checkBox_54")
        self.gridLayout_2.addWidget(self.checkBox_54, 12, 1, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_2.addWidget(self.checkBox_10, 0, 2, 1, 1)
        self.checkBox_27 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_27.setObjectName("checkBox_27")
        self.gridLayout_2.addWidget(self.checkBox_27, 2, 2, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_2.addWidget(self.checkBox_16, 5, 0, 1, 1)
        self.checkBox_49 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_49.setObjectName("checkBox_49")
        self.gridLayout_2.addWidget(self.checkBox_49, 9, 1, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_2.addWidget(self.checkBox_8, 0, 0, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_2.addWidget(self.checkBox_13, 2, 0, 1, 1)
        self.checkBox_59 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_59.setObjectName("checkBox_59")
        self.gridLayout_2.addWidget(self.checkBox_59, 11, 3, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout_2.addWidget(self.checkBox_19, 8, 0, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout_2.addWidget(self.checkBox_18, 7, 0, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_31.setObjectName("checkBox_31")
        self.gridLayout_2.addWidget(self.checkBox_31, 2, 3, 1, 1)
        self.checkBox_53 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_53.setObjectName("checkBox_53")
        self.gridLayout_2.addWidget(self.checkBox_53, 10, 3, 1, 1)
        self.checkBox_57 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_57.setObjectName("checkBox_57")
        self.gridLayout_2.addWidget(self.checkBox_57, 11, 1, 1, 1)
        self.checkBox_32 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout_2.addWidget(self.checkBox_32, 3, 3, 1, 1)
        self.checkBox_58 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_58.setObjectName("checkBox_58")
        self.gridLayout_2.addWidget(self.checkBox_58, 11, 2, 1, 1)
        self.checkBox_60 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_60.setObjectName("checkBox_60")
        self.gridLayout_2.addWidget(self.checkBox_60, 13, 0, 1, 1)
        self.checkBox_61 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_61.setObjectName("checkBox_61")
        self.gridLayout_2.addWidget(self.checkBox_61, 13, 1, 1, 1)
        self.checkBox_62 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_62.setObjectName("checkBox_62")
        self.gridLayout_2.addWidget(self.checkBox_62, 13, 2, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 13, 3, 1, 1)
        self.formLayout.setLayout(9, QtWidgets.QFormLayout.FieldRole, self.gridLayout_2)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.label_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(11, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "API Key"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt;\">Pour avoir une clef d\'API vous devez vous créer un compte sur : </span><a href=\"https://newsapi.org/\"><span style=\" font-size:9pt; font-weight:600; text-decoration: underline; color:#0000ff;\">News API</span></a></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "Catégorie :"))
        self.checkBox.setText(_translate("Dialog", "Business"))
        self.checkBox_4.setText(_translate("Dialog", "Entertainement"))
        self.checkBox_2.setText(_translate("Dialog", "General"))
        self.checkBox_3.setText(_translate("Dialog", "Santé"))
        self.checkBox_5.setText(_translate("Dialog", "Science"))
        self.checkBox_7.setText(_translate("Dialog", "Sport"))
        self.checkBox_6.setText(_translate("Dialog", "Technologie"))
        self.label_3.setText(_translate("Dialog", "Pays :"))
        self.checkBox_50.setText(_translate("Dialog", "ro"))
        self.checkBox_38.setText(_translate("Dialog", "in"))
        self.checkBox_55.setText(_translate("Dialog", "ua"))
        self.checkBox_23.setText(_translate("Dialog", "tr"))
        self.checkBox_41.setText(_translate("Dialog", "lt"))
        self.checkBox_17.setText(_translate("Dialog", "it"))
        self.checkBox_26.setText(_translate("Dialog", "cn"))
        self.checkBox_15.setText(_translate("Dialog", "gb"))
        self.checkBox_52.setText(_translate("Dialog", "sa"))
        self.checkBox_47.setText(_translate("Dialog", "no"))
        self.checkBox_24.setText(_translate("Dialog", "de"))
        self.checkBox_44.setText(_translate("Dialog", "pt"))
        self.checkBox_46.setText(_translate("Dialog", "nz"))
        self.checkBox_43.setText(_translate("Dialog", "mx"))
        self.checkBox_30.setText(_translate("Dialog", "ca"))
        self.checkBox_22.setText(_translate("Dialog", "sg"))
        self.checkBox_28.setText(_translate("Dialog", "bg"))
        self.checkBox_9.setText(_translate("Dialog", "ar"))
        self.checkBox_29.setText(_translate("Dialog", "br"))
        self.checkBox_21.setText(_translate("Dialog", "rs"))
        self.checkBox_12.setText(_translate("Dialog", "be"))
        self.checkBox_36.setText(_translate("Dialog", "ie"))
        self.checkBox_20.setText(_translate("Dialog", "ph"))
        self.checkBox_37.setText(_translate("Dialog", "il"))
        self.checkBox_33.setText(_translate("Dialog", "gr"))
        self.checkBox_14.setText(_translate("Dialog", "cz"))
        self.checkBox_11.setText(_translate("Dialog", "au"))
        self.checkBox_56.setText(_translate("Dialog", "us"))
        self.checkBox_34.setText(_translate("Dialog", "hk"))
        self.checkBox_51.setText(_translate("Dialog", "ru"))
        self.checkBox_45.setText(_translate("Dialog", "my"))
        self.checkBox_42.setText(_translate("Dialog", "ma"))
        self.checkBox_40.setText(_translate("Dialog", "kr"))
        self.checkBox_25.setText(_translate("Dialog", "eg"))
        self.checkBox_48.setText(_translate("Dialog", "nl"))
        self.checkBox_39.setText(_translate("Dialog", "jp"))
        self.checkBox_35.setText(_translate("Dialog", "hu"))
        self.checkBox_54.setText(_translate("Dialog", "tw"))
        self.checkBox_10.setText(_translate("Dialog", "at"))
        self.checkBox_27.setText(_translate("Dialog", "co"))
        self.checkBox_16.setText(_translate("Dialog", "id"))
        self.checkBox_49.setText(_translate("Dialog", "pl"))
        self.checkBox_8.setText(_translate("Dialog", "ae"))
        self.checkBox_13.setText(_translate("Dialog", "ch"))
        self.checkBox_59.setText(_translate("Dialog", "th"))
        self.checkBox_19.setText(_translate("Dialog", "ng"))
        self.checkBox_18.setText(_translate("Dialog", "lv"))
        self.checkBox_31.setText(_translate("Dialog", "cu"))
        self.checkBox_53.setText(_translate("Dialog", "se"))
        self.checkBox_57.setText(_translate("Dialog", "si"))
        self.checkBox_32.setText(_translate("Dialog", "fr"))
        self.checkBox_58.setText(_translate("Dialog", "sk"))
        self.checkBox_60.setText(_translate("Dialog", "us"))
        self.checkBox_61.setText(_translate("Dialog", "ve"))
        self.checkBox_62.setText(_translate("Dialog", "za"))
        self.radioButton.setText(_translate("Dialog", "Tout"))
        self.label_5.setText(_translate("Dialog", "Nom des pays en norme ISO 3166-1"))
